/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AturRouteImport } from './routes/atur'
import { Route as EvaluasiRouteImport } from './routes/evaluasi'
import { Route as KonfirmasiRouteImport } from './routes/konfirmasi'
import { Route as RencanaRouteImport } from './routes/rencana'
import { Route as RiwayatRouteImport } from './routes/riwayat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AturRoute = AturRouteImport.update({
  id: '/atur',
  path: '/atur',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluasiRoute = EvaluasiRouteImport.update({
  id: '/evaluasi',
  path: '/evaluasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KonfirmasiRoute = KonfirmasiRouteImport.update({
  id: '/konfirmasi',
  path: '/konfirmasi',
  getParentRoute: () => rootRouteImport,
} as any)
const RencanaRoute = RencanaRouteImport.update({
  id: '/rencana',
  path: '/rencana',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atur': typeof AturRoute
  '/evaluasi': typeof EvaluasiRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/rencana': typeof RencanaRoute
  '/riwayat': typeof RiwayatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atur': typeof AturRoute
  '/evaluasi': typeof EvaluasiRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/rencana': typeof RencanaRoute
  '/riwayat': typeof RiwayatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atur': typeof AturRoute
  '/evaluasi': typeof EvaluasiRoute
  '/konfirmasi': typeof KonfirmasiRoute
  '/rencana': typeof RencanaRoute
  '/riwayat': typeof RiwayatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/atur' | '/evaluasi' | '/konfirmasi' | '/rencana' | '/riwayat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atur' | '/evaluasi' | '/konfirmasi' | '/rencana' | '/riwayat'
  id:
    | '__root__'
    | '/'
    | '/atur'
    | '/evaluasi'
    | '/konfirmasi'
    | '/rencana'
    | '/riwayat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AturRoute: typeof AturRoute
  EvaluasiRoute: typeof EvaluasiRoute
  KonfirmasiRoute: typeof KonfirmasiRoute
  RencanaRoute: typeof RencanaRoute
  RiwayatRoute: typeof RiwayatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atur': {
      id: '/atur'
      path: '/atur'
      fullPath: '/atur'
      preLoaderRoute: typeof AturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluasi': {
      id: '/evaluasi'
      path: '/evaluasi'
      fullPath: '/evaluasi'
      preLoaderRoute: typeof EvaluasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konfirmasi': {
      id: '/konfirmasi'
      path: '/konfirmasi'
      fullPath: '/konfirmasi'
      preLoaderRoute: typeof KonfirmasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rencana': {
      id: '/rencana'
      path: '/rencana'
      fullPath: '/rencana'
      preLoaderRoute: typeof RencanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AturRoute: AturRoute,
  EvaluasiRoute: EvaluasiRoute,
  KonfirmasiRoute: KonfirmasiRoute,
  RencanaRoute: RencanaRoute,
  RiwayatRoute: RiwayatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
